### ISSUE TITLE
Is the demo fake?

### ISSUE THREAD

**Issue by 5twenty9** [davabase/transcriber_app#31]
Demo shows transcription of a video, which is sound from speakers.
App is supposed to do transcription from microphone. I am understanding wrong or is the demo fake?

**Comment by davabase** [comment]
The demo is not fake, the app can transcribe from any input audio source. If your sound card supports loopback then you can use Stereo Mix as an input, see [this issue](https://github.com/davabase/transcriber_app/issues/11). There are also numerous applications that support piping audio to others sources such as [BlackHole](https://github.com/ExistentialAudio/BlackHole) on Mac.

**Comment by 5twenty9** [comment]
Good to know.
Out of the box app does not show any speakers only input devices :-(.
So demo is a special use case of the app.
