### ISSUE TITLE
CUDA not available?

### ISSUE THREAD

**Issue by InconsolableCellist** [davabase/transcriber_app#9]
Is there any documentation or log output that would indicate if the standalone program is trying to use CUDA and failing? What do I need to install other than the NVIDIA Cuda 11 library to make it use GPU acceleration? It seems that the CPU on my gaming laptop is too slow to do realtime transcription.

**Comment by davabase** [comment]
I just made a [change](https://github.com/davabase/transcriber_app/commit/94eb17fafc7bff584cd9052b64e9f96a99e5f39b), that will make the program prefer CUDA if a CUDA device is available.
